### ISSUE TITLE
Only allow users to link a Gmail account with all permissions

### ISSUE THREAD

**Issue by NickkTMD** [tiki/strategy_google#86]
#77 has some relevant info

As a user, I should not be allowed to login unless I give app permission to read and send emails for me. When I log in with google, these permissions should be checked by default, and login should not be possible if they are unchecked (ideally it should be impossible for users to uncheck them).

Acceptance Crit
1. Users can only log in to google account if they give required permissions to app

**Comment by ricardobrg** [comment]
#77 implements this verification properly and 
#76 will implement the UI explaining the user why the account wasn't linked.

For this issue we must make sure that it is possible to ask for more permissions and do it all in the background. 
1. Normal oauth login flow
2. When the user is redirected to the app we ask for additional scopes.

It could have a different state for the accounts: if the account is connected but user didn't allow all scopes.

This issue requires 2 more steps
1. Verify if it is possible to require additional scopes. If possible implement it in the account linking flow.
2. Design  and implement UX for partially authorized account

**Comment by ricardobrg** [comment]
closing this in favor of #88
